name: Lint and Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install black flake8 isort

      - name: Run Black (formatter)
        run: black --check src/

      - name: Run isort (import sorting)
        run: isort --check-only src/

      - name: Run Flake8 (linter)
        run: flake8 src/
