name: Build Executable for Linux and Windows

on:
  pull_request: 

jobs:
  build-linux:
    name: Build Linux Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable (Linux)
        run: |
          pyinstaller --onefile ./src/main.py --name OmnAIView-Python-Linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmnAIView-Linux
          path: dist/OmnAIView-Python-Linux

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable (Windows)
        run: |
          pyinstaller --onefile .\src\main.py --name OmnAIView-Python-Windows
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmnAIView-Windows
          path: dist\OmnAIView-Python-Windows